### ISSUE TITLE
item不一样大怎么办

### ISSUE THREAD

**Issue by chenzixue** [yanyusong/Y_DividerItemDecoration#2]
GridLayoutManager布局,2列。i%2==0时设置右边距和下边距，i%2==1时只设置下边距，发现左边的item比右边的小。如果i%2==0设置右边距和下边距，i%2==1设置左边距和下边距。垂直边距和横向边距又不一样大

**Comment by yanyusong** [comment]
是的，确实存在这样的问题，我刚仔细想了一下GridLayout2列的话，item宽度是等分屏幕宽度的没错，但是分割线作为itemDecoration实际上是占用了item的宽度的了，分割线细的话可能看不太明显，分割线粗了估计就很明显了，我现在已经想好了几种方案来，请持续关注，很快就会更新

**Comment by chenzixue** [comment]
更新真快！！！

**Comment by yanyusong** [comment]
代码提交过了，但是文档已经落后好久了，一直没时间更新，真是太抱歉了，你运行demo试过了吗？有问题可以跟我联系，我尽快更新文档

**Comment by yanyusong** [comment]
2.0版文档已更新

**Comment by chenzixue** [comment]
感谢回复！运行过了，没有问题
